openapi: 3.1.0
info:
  title: Journal Assistant API
  version: 2.0.0
jsonSchemaDialect: https://json-schema.org/draft/2020-12/schema
servers:
  - url: https://ptglegpphtedkqrbzjym.supabase.co/rest/v1
paths:
  /journal_entries:
    post:
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/apikey'
      operationId: createJournalEntry
      summary: Add a new journal entry
      tags: [Journal]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JournalEntry'
      responses:
        '201':
          description: Journal entry created

  /events:
    post:
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/apikey'
      operationId: createEvent
      summary: Add a new event
      tags: [Events]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: Event created

  /journal_insights:
    post:
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/apikey'
      operationId: addInsight
      summary: Add AI-generated insight to a journal entry
      tags: [Journal]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insight'
      responses:
        '201':
          description: Insight added

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    apikey:
      name: apikey
      in: header
      required: true
      schema:
        type: string
  schemas:
    JournalEntry:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
        content:
          type: string
        summary:
          type: string
        topics:
          type: array
          items:
            type: string
        media_url:
          type: string
        pinned:
          type: boolean

    Event:
      type: object
      properties:
        user_id:
          type: string
        title:
          type: string
        description:
          type: string
        event_date:
          type: string
          format: date

    Insight:
      type: object
      properties:
        journal_entry_id:
          type: string
          format: uuid
        insight:
          type: string
